### ISSUE TITLE
Error during installation ("ValueError: No closing quotation")

### ISSUE THREAD

**Issue by fr33tux** [labriqueinternet/hotspot_ynh#18]
There's an error at the end of the installation, during the script execution :

```
Traceback (most recent call last):
  File "/usr/lib/moulinette/yunohost/app.py", line 482, in app_install
    if hook_exec(app_tmp_folder + '/scripts/install', args_dict) == 0:
  File "/usr/lib/moulinette/yunohost/hook.py", line 313, in hook_exec
    file_path, file, arg_str)),
  File "/usr/lib/python2.7/shlex.py", line 279, in split
    return list(lex)
  File "/usr/lib/python2.7/shlex.py", line 269, in next
    token = self.get_token()
  File "/usr/lib/python2.7/shlex.py", line 96, in get_token
    raw = self.read_token()
  File "/usr/lib/python2.7/shlex.py", line 172, in read_token
    raise ValueError, "No closing quotation"
ValueError: No closing quotation

**Comment by opi** [comment]
I don't know why I was assigned to a python issue ;)   but googling the error message give me "No closing quotation error because `#` is treated as a comment even inside a string". Could be something to look after.

**Comment by jvaubourg** [comment]
I assigned this issue to you (then @Kloadut, I thought be able to add several people) just because this seemed to be a YunoHost related issue :).

**Comment by jvaubourg** [comment]
No idea?
