### ISSUE TITLE
"Wifi hotspot" Installation failed

### ISSUE THREAD

**Issue by pascal-levasseur** [labriqueinternet/hotspot_ynh#80]
On a brand new installation of Yunohost the installation of "Wifi Hotspot"application using web admin failed.

Hardware : Old Laptop Compaq  8510p Intel Centrino CPU
Acces : Installation made with web admin
Version : Yunohost 4.2.8.3
Special context : Brand new installation of Yunohost
No tweaking at all.

Log 

2021-09-16 13:42:20,532: DEBUG - + match_string=__FINALPATH__
2021-09-16 13:42:20,533: DEBUG - + replace_string=/var/www/hotspot
2021-09-16 13:42:20,533: DEBUG - + sed --in-place s@__FINALPATH__@/var/www/hotspot@g /var/www/hotspot/config.php
2021-09-16 13:42:20,535: DEBUG - + test -n 7.3
2021-09-16 13:42:20,535: DEBUG - + ynh_replace_string --match_string=__PHPVERSION__ --replace_string=7.3 --target_file=/var/www/hotspot/config.php
2021-09-16 13:42:20,637: DEBUG - + local delimit=@
2021-09-16 13:42:20,638: DEBUG - + match_string=__PHPVERSION__
2021-09-16 13:42:20,638: DEBUG - + replace_string=7.3
2021-09-16 13:42:20,638: DEBUG - + sed --in-place s@__PHPVERSION__@7.3@g /var/www/hotspot/config.php
2021-09-16 13:42:20,641: DEBUG - + test -n ''
2021-09-16 13:42:20,641: DEBUG - + uniques_vars=($(grep -oP '__[A-Z0-9]+?[A-Z0-9_]*?[A-Z0-9]*?__' $file | sort --unique | sed "s@__\([^.]*\)__@\L\1@g" ))
2021-09-16 13:42:20,642: DEBUG - ++ grep -oP '__[A-Z0-9]+?[A-Z0-9_]*?[A-Z0-9]*?__' /var/www/hotspot/config.php
2021-09-16 13:42:20,642: DEBUG - ++ sed 's@__\([^.]*\)__@\L\1@g'
2021-09-16 13:42:20,646: DEBUG - ++ sort --unique
2021-09-16 13:42:20,649: DEBUG - + local delimit=@
2021-09-16 13:42:20,650: DEBUG - + for one_var in "${uniques_vars[@]}"
2021-09-16 13:42:20,650: DEBUG - + [[ -v final_path ]]
2021-09-16 13:42:20,650: DEBUG - + match_string=__FINAL_PATH__
2021-09-16 13:42:20,650: DEBUG - + match_string=__FINAL_PATH__
2021-09-16 13:42:20,650: DEBUG - + replace_string=/var/www/hotspot
2021-09-16 13:42:20,650: DEBUG - + replace_string=/var/www/hotspot
2021-09-16 13:42:20,651: DEBUG - + replace_string=/var/www/hotspot
2021-09-16 13:42:20,651: DEBUG - + sed --in-place s@__FINAL_PATH__@/var/www/hotspot@g /var/www/hotspot/config.php
2021-09-16 13:42:20,652: DEBUG - + ynh_store_file_checksum --file=/var/www/hotspot/config.php
2021-09-16 13:42:20,664: DEBUG - + local checksum_setting_name=checksum__var_www_hotspot_config.php
2021-09-16 13:42:20,665: DEBUG - ++ md5sum /var/www/hotspot/config.php
2021-09-16 13:42:20,665: DEBUG - ++ cut '--delimiter= ' --fields=1
2021-09-16 13:42:20,668: DEBUG - + ynh_app_setting_set --app=hotspot --key=checksum__var_www_hotspot_config.php --value=189c81442c2a305118150994ac4e7c82
2021-09-16 13:42:20,764: DEBUG - + [[ checksum__var_www_hotspot_config.php =~ (unprotected|protected|skipped)_ ]]
2021-09-16 13:42:20,765: DEBUG - + ynh_app_setting set hotspot checksum__var_www_hotspot_config.php 189c81442c2a305118150994ac4e7c82
2021-09-16 13:42:20,837: DEBUG - + '[' -n '' ']'
2021-09-16 13:42:20,838: DEBUG - + unset backup_file_checksum
2021-09-16 13:42:20,838: DEBUG - + chown hotspot:hotspot /var/www/hotspot/config.php
2021-09-16 13:42:20,840: DEBUG - + systemctl disable hostapd --quiet
2021-09-16 13:42:21,810: DEBUG - + systemctl stop hostapd
2021-09-16 13:42:21,819: DEBUG - + systemctl unmask hostapd
2021-09-16 13:42:21,826: WARNING - Removed /etc/systemd/system/hostapd.service.
2021-09-16 13:42:22,181: DEBUG - + echo '[##############+.....] > Storing the config file checksum...'
2021-09-16 13:42:22,182: INFO - [##############+.....] > Storing the config file checksum...
2021-09-16 13:42:22,183: DEBUG - + ynh_store_file_checksum --file=/etc/init.d/hostapd
2021-09-16 13:42:22,196: DEBUG - + local checksum_setting_name=checksum__etc_init.d_hostapd
2021-09-16 13:42:22,197: DEBUG - ++ md5sum /etc/init.d/hostapd
2021-09-16 13:42:22,198: DEBUG - ++ cut '--delimiter= ' --fields=1
2021-09-16 13:42:22,200: DEBUG - + ynh_app_setting_set --app=hotspot --key=checksum__etc_init.d_hostapd --value=6d5e58c4117fe4a97b04b5bc151f19d6
2021-09-16 13:42:22,301: DEBUG - + [[ checksum__etc_init.d_hostapd =~ (unprotected|protected|skipped)_ ]]
2021-09-16 13:42:22,302: DEBUG - + ynh_app_setting set hotspot checksum__etc_init.d_hostapd 6d5e58c4117fe4a97b04b5bc151f19d6
2021-09-16 13:42:22,374: DEBUG - + '[' -n '' ']'
2021-09-16 13:42:22,375: DEBUG - + unset backup_file_checksum
2021-09-16 13:42:22,435: DEBUG - + echo '[###############+....] > Configuring a systemd service...'
2021-09-16 13:42:22,436: INFO - [###############+....] > Configuring a systemd service...
2021-09-16 13:42:22,436: DEBUG - + ynh_add_systemd_config --service=ynh-hotspot
2021-09-16 13:42:22,475: DEBUG - + service=ynh-hotspot
2021-09-16 13:42:22,476: DEBUG - + template=systemd.service
2021-09-16 13:42:22,476: DEBUG - + others_var=
2021-09-16 13:42:22,476: DEBUG - + [[ -z '' ]]
2021-09-16 13:42:22,476: DEBUG - + ynh_add_config --template=/var/cache/yunohost/app_tmp_work_dirs/app_phe3qx79/conf/systemd.service --destination=/etc/systemd/system/ynh-hotspot.service
2021-09-16 13:42:22,524: DEBUG - + '[' -f /var/cache/yunohost/app_tmp_work_dirs/app_phe3qx79/conf//var/cache/yunohost/app_tmp_work_dirs/app_phe3qx79/conf/systemd.service ']'
2021-09-16 13:42:22,524: DEBUG - + '[' -f /var/cache/yunohost/app_tmp_work_dirs/app_phe3qx79/conf/systemd.service ']'
2021-09-16 13:42:22,524: DEBUG - + template_path=/var/cache/yunohost/app_tmp_work_dirs/app_phe3qx79/conf/systemd.service
2021-09-16 13:42:22,525: DEBUG - + ynh_backup_if_checksum_is_different --file=/etc/systemd/system/ynh-hotspot.service
2021-09-16 13:42:22,539: DEBUG - + local checksum_setting_name=checksum__etc_systemd_system_ynh-hotspot.service
2021-09-16 13:42:22,539: DEBUG - ++ ynh_app_setting_get --app=hotspot --key=checksum__etc_systemd_system_ynh-hotspot.service
2021-09-16 13:42:22,586: DEBUG - ++ [[ checksum__etc_systemd_system_ynh-hotspot.service =~ (unprotected|protected|skipped)_ ]]
2021-09-16 13:42:22,587: DEBUG - ++ ynh_app_setting get hotspot checksum__etc_systemd_system_ynh-hotspot.service
2021-09-16 13:42:22,658: DEBUG - + local checksum_value=
2021-09-16 13:42:22,658: DEBUG - + backup_file_checksum=
2021-09-16 13:42:22,658: DEBUG - + '[' -n '' ']'
2021-09-16 13:42:22,659: DEBUG - + touch /etc/systemd/system/ynh-hotspot.service
2021-09-16 13:42:22,659: DEBUG - + chown root:root /etc/systemd/system/ynh-hotspot.service
2021-09-16 13:42:22,661: DEBUG - + chmod 640 /etc/systemd/system/ynh-hotspot.service
2021-09-16 13:42:22,662: DEBUG - + cp -f /var/cache/yunohost/app_tmp_work_dirs/app_phe3qx79/conf/systemd.service /etc/systemd/system/ynh-hotspot.service
2021-09-16 13:42:22,664: DEBUG - + _ynh_apply_default_permissions /etc/systemd/system/ynh-hotspot.service
2021-09-16 13:42:22,664: DEBUG - + local target=/etc/systemd/system/ynh-hotspot.service
2021-09-16 13:42:22,665: DEBUG - ++ jq -r .requirements.yunohost /var/cache/yunohost/app_tmp_work_dirs/app_phe3qx79/manifest.json
2021-09-16 13:42:22,665: DEBUG - ++ tr -d '>= '
2021-09-16 13:42:22,671: DEBUG - + local ynh_requirement=4.1.0
2021-09-16 13:42:22,672: DEBUG - + '[' -z 4.1.0 ']'
2021-09-16 13:42:22,672: DEBUG - + '[' 4.1.0 == null ']'
2021-09-16 13:42:22,672: DEBUG - + dpkg --compare-versions 4.1.0 ge 4.2
2021-09-16 13:42:22,675: DEBUG - + ynh_replace_vars --file=/etc/systemd/system/ynh-hotspot.service
2021-09-16 13:42:22,691: DEBUG - + test -n /wifiadmin
2021-09-16 13:42:22,691: DEBUG - + local path_url_slash_less=/wifiadmin
2021-09-16 13:42:22,691: DEBUG - + ynh_replace_string --match_string=__PATH__/ --replace_string=/wifiadmin/ --target_file=/etc/systemd/system/ynh-hotspot.service
2021-09-16 13:42:22,784: DEBUG - + local delimit=@
2021-09-16 13:42:22,785: DEBUG - + match_string=__PATH__/
2021-09-16 13:42:22,787: DEBUG - + replace_string=/wifiadmin/
2021-09-16 13:42:22,787: DEBUG - + sed --in-place s@__PATH__/@/wifiadmin/@g /etc/systemd/system/ynh-hotspot.service
2021-09-16 13:42:22,788: DEBUG - + ynh_replace_string --match_string=__PATH__ --replace_string=/wifiadmin --target_file=/etc/systemd/system/ynh-hotspot.service
2021-09-16 13:42:22,871: DEBUG - + local delimit=@
2021-09-16 13:42:22,872: DEBUG - + match_string=__PATH__
2021-09-16 13:42:22,872: DEBUG - + replace_string=/wifiadmin
2021-09-16 13:42:22,872: DEBUG - + sed --in-place s@__PATH__@/wifiadmin@g /etc/systemd/system/ynh-hotspot.service
2021-09-16 13:42:22,874: DEBUG - + test -n hotspot
2021-09-16 13:42:22,875: DEBUG - + ynh_replace_string --match_string=__NAME__ --replace_string=hotspot --target_file=/etc/systemd/system/ynh-hotspot.service
2021-09-16 13:42:22,968: DEBUG - + local delimit=@
2021-09-16 13:42:22,968: DEBUG - + match_string=__NAME__
2021-09-16 13:42:22,968: DEBUG - + replace_string=hotspot
2021-09-16 13:42:22,969: DEBUG - + sed --in-place s@__NAME__@hotspot@g /etc/systemd/system/ynh-hotspot.service
2021-09-16 13:42:22,971: DEBUG - + ynh_replace_string --match_string=__NAMETOCHANGE__ --replace_string=hotspot --target_file=/etc/systemd/system/ynh-hotspot.service
2021-09-16 13:42:23,068: DEBUG - + local delimit=@
2021-09-16 13:42:23,068: DEBUG - + match_string=__NAMETOCHANGE__
2021-09-16 13:42:23,069: DEBUG - + replace_string=hotspot
2021-09-16 13:42:23,069: DEBUG - + sed --in-place s@__NAMETOCHANGE__@hotspot@g /etc/systemd/system/ynh-hotspot.service
2021-09-16 13:42:23,071: DEBUG - + ynh_replace_string --match_string=__USER__ --replace_string=hotspot --target_file=/etc/systemd/system/ynh-hotspot.service
2021-09-16 13:42:23,168: DEBUG - + local delimit=@
2021-09-16 13:42:23,169: DEBUG - + match_string=__USER__
2021-09-16 13:42:23,169: DEBUG - + replace_string=hotspot
2021-09-16 13:42:23,169: DEBUG - + sed --in-place s@__USER__@hotspot@g /etc/systemd/system/ynh-hotspot.service
2021-09-16 13:42:23,172: DEBUG - + test -n /var/www/hotspot
2021-09-16 13:42:23,172: DEBUG - + ynh_replace_string --match_string=__FINALPATH__ --replace_string=/var/www/hotspot --target_file=/etc/systemd/system/ynh-hotspot.service
2021-09-16 13:42:23,270: DEBUG - + local delimit=@
2021-09-16 13:42:23,270: DEBUG - + match_string=__FINALPATH__
2021-09-16 13:42:23,271: DEBUG - + replace_string=/var/www/hotspot
2021-09-16 13:42:23,271: DEBUG - + sed --in-place s@__FINALPATH__@/var/www/hotspot@g /etc/systemd/system/ynh-hotspot.service
2021-09-16 13:42:23,273: DEBUG - + test -n 7.3
2021-09-16 13:42:23,274: DEBUG - + ynh_replace_string --match_string=__PHPVERSION__ --replace_string=7.3 --target_file=/etc/systemd/system/ynh-hotspot.service
2021-09-16 13:42:23,371: DEBUG - + local delimit=@
2021-09-16 13:42:23,371: DEBUG - + match_string=__PHPVERSION__
2021-09-16 13:42:23,371: DEBUG - + replace_string=7.3
2021-09-16 13:42:23,372: DEBUG - + sed --in-place s@__PHPVERSION__@7.3@g /etc/systemd/system/ynh-hotspot.service
2021-09-16 13:42:23,374: DEBUG - + test -n ''
2021-09-16 13:42:23,374: DEBUG - + uniques_vars=($(grep -oP '__[A-Z0-9]+?[A-Z0-9_]*?[A-Z0-9]*?__' $file | sort --unique | sed "s@__\([^.]*\)__@\L\1@g" ))
2021-09-16 13:42:23,375: DEBUG - ++ grep -oP '__[A-Z0-9]+?[A-Z0-9_]*?[A-Z0-9]*?__' /etc/systemd/system/ynh-hotspot.service
2021-09-16 13:42:23,376: DEBUG - ++ sed 's@__\([^.]*\)__@\L\1@g'
2021-09-16 13:42:23,379: DEBUG - ++ sort --unique
2021-09-16 13:42:23,382: DEBUG - + local delimit=@
2021-09-16 13:42:23,382: DEBUG - + ynh_store_file_checksum --file=/etc/systemd/system/ynh-hotspot.service
2021-09-16 13:42:23,395: DEBUG - + local checksum_setting_name=checksum__etc_systemd_system_ynh-hotspot.service
2021-09-16 13:42:23,396: DEBUG - ++ md5sum /etc/systemd/system/ynh-hotspot.service
2021-09-16 13:42:23,397: DEBUG - ++ cut '--delimiter= ' --fields=1
2021-09-16 13:42:23,401: DEBUG - + ynh_app_setting_set --app=hotspot --key=checksum__etc_systemd_system_ynh-hotspot.service --value=3ec37a03bda4c3950c38a1e720a88f08
2021-09-16 13:42:23,497: DEBUG - + [[ checksum__etc_systemd_system_ynh-hotspot.service =~ (unprotected|protected|skipped)_ ]]
2021-09-16 13:42:23,497: DEBUG - + ynh_app_setting set hotspot checksum__etc_systemd_system_ynh-hotspot.service 3ec37a03bda4c3950c38a1e720a88f08
2021-09-16 13:42:23,574: DEBUG - + '[' -n '' ']'
2021-09-16 13:42:23,574: DEBUG - + unset backup_file_checksum
2021-09-16 13:42:23,574: DEBUG - + systemctl enable ynh-hotspot --quiet
2021-09-16 13:42:23,857: DEBUG - + systemctl daemon-reload
2021-09-16 13:42:24,132: DEBUG - + [[ none != none ]]
2021-09-16 13:42:24,196: DEBUG - + echo '[################+...] > Integrating service in YunoHost...'
2021-09-16 13:42:24,197: INFO - [################+...] > Integrating service in YunoHost...
2021-09-16 13:42:24,198: DEBUG - + yunohost service add ynh-hotspot --description 'Creates a Wi-Fi access point' --test_status 'systemctl is-active hostapd'
2021-09-16 13:42:24,438: DEBUG - Le service 'ynh-hotspot' a été ajouté
2021-09-16 13:42:24,544: DEBUG - + echo '[#################+..] > Starting a systemd service...'
2021-09-16 13:42:24,544: INFO - [#################+..] > Starting a systemd service...
2021-09-16 13:42:24,545: DEBUG - + [[ wlp16s0 == none ]]
2021-09-16 13:42:24,545: DEBUG - + ynh_systemd_action --service_name=ynh-hotspot --action=start --log_path=systemd
2021-09-16 13:42:24,725: DEBUG - + service_name=ynh-hotspot
2021-09-16 13:42:24,726: DEBUG - + action=start
2021-09-16 13:42:24,726: DEBUG - + line_match=
2021-09-16 13:42:24,726: DEBUG - + length=20
2021-09-16 13:42:24,726: DEBUG - + log_path=systemd
2021-09-16 13:42:24,726: DEBUG - + timeout=300
2021-09-16 13:42:24,727: DEBUG - + '[' start == stop ']'
2021-09-16 13:42:24,727: DEBUG - + [[ -n '' ]]
2021-09-16 13:42:24,727: DEBUG - + '[' start == reload ']'
2021-09-16 13:42:24,727: DEBUG - + systemctl start ynh-hotspot
2021-09-16 13:42:25,807: WARNING - Job for ynh-hotspot.service failed because the control process exited with error code.
2021-09-16 13:42:25,808: WARNING - See "systemctl status ynh-hotspot.service" and "journalctl -xe" for details.
2021-09-16 13:42:25,809: DEBUG - + ynh_exec_err journalctl --quiet --no-hostname --no-pager --lines=20 --unit=ynh-hotspot
2021-09-16 13:42:25,809: DEBUG - ++ eval journalctl --quiet --no-hostname --no-pager --lines=20 --unit=ynh-hotspot
2021-09-16 13:42:25,809: DEBUG - +++ journalctl --quiet --no-hostname --no-pager --lines=20 --unit=ynh-hotspot
2021-09-16 13:42:25,819: DEBUG - + ynh_print_err 'sept. 16 13:42:24 systemd[1]: Starting YunoHost Wifi Hotspot...
2021-09-16 13:42:25,819: DEBUG - sept. 16 13:42:24 ynh-hotspot[8084]: Retrieving Yunohost settings... OK
2021-09-16 13:42:25,820: DEBUG - sept. 16 13:42:24 ynh-hotspot[8084]: [hotspot] Starting...
2021-09-16 13:42:25,820: DEBUG - sept. 16 13:42:25 ynh-hotspot[8084]: Traceback (most recent call last):
2021-09-16 13:42:25,820: DEBUG - sept. 16 13:42:25 ynh-hotspot[8084]:   File "<stdin>", line 1, in <module>
2021-09-16 13:42:25,820: DEBUG - sept. 16 13:42:25 ynh-hotspot[8084]: ImportError: No module named yaml
2021-09-16 13:42:25,820: DEBUG - sept. 16 13:42:25 ynh-hotspot[8084]: Set NAT
2021-09-16 13:42:25,821: DEBUG - sept. 16 13:42:25 ynh-hotspot[8084]: Set forwarding
2021-09-16 13:42:25,821: DEBUG - sept. 16 13:42:25 ynh-hotspot[8084]: Run hostapd
2021-09-16 13:42:25,821: DEBUG - sept. 16 13:42:25 ynh-hotspot[8084]: Job for hostapd.service failed because the control process exited with error code.
2021-09-16 13:42:25,821: DEBUG - sept. 16 13:42:25 ynh-hotspot[8084]: See "systemctl status hostapd.service" and "journalctl -xe" for details.
2021-09-16 13:42:25,821: DEBUG - sept. 16 13:42:25 systemd[1]: ynh-hotspot.service: Main process exited, code=exited, status=1/FAILURE
2021-09-16 13:42:25,822: DEBUG - sept. 16 13:42:25 systemd[1]: ynh-hotspot.service: Failed with result '\''exit-code'\''.
2021-09-16 13:42:25,822: DEBUG - sept. 16 13:42:25 systemd[1]: Failed to start YunoHost Wifi Hotspot.'
2021-09-16 13:42:25,823: DEBUG - sept. 16 13:42:24 ynh-hotspot[8084]: Retrieving Yunohost settings... OK
2021-09-16 13:42:25,823: DEBUG - sept. 16 13:42:24 ynh-hotspot[8084]: [hotspot] Starting...
2021-09-16 13:42:25,823: DEBUG - sept. 16 13:42:25 ynh-hotspot[8084]: Traceback (most recent call last):
2021-09-16 13:42:25,823: DEBUG - sept. 16 13:42:25 ynh-hotspot[8084]:   File "<stdin>", line 1, in <module>
2021-09-16 13:42:25,823: DEBUG - sept. 16 13:42:25 ynh-hotspot[8084]: ImportError: No module named yaml
2021-09-16 13:42:25,824: DEBUG - sept. 16 13:42:25 ynh-hotspot[8084]: Set NAT
2021-09-16 13:42:25,824: DEBUG - sept. 16 13:42:25 ynh-hotspot[8084]: Set forwarding
2021-09-16 13:42:25,824: DEBUG - sept. 16 13:42:25 ynh-hotspot[8084]: Run hostapd
2021-09-16 13:42:25,824: DEBUG - sept. 16 13:42:25 ynh-hotspot[8084]: Job for hostapd.service failed because the control process exited with error code.
2021-09-16 13:42:25,824: DEBUG - sept. 16 13:42:25 ynh-hotspot[8084]: See "systemctl status hostapd.service" and "journalctl -xe" for details.
2021-09-16 13:42:25,825: DEBUG - sept. 16 13:42:25 systemd[1]: ynh-hotspot.service: Main process exited, code=exited, status=1/FAILURE
2021-09-16 13:42:25,825: DEBUG - sept. 16 13:42:25 systemd[1]: ynh-hotspot.service: Failed with result '\''exit-code'\''.
2021-09-16 13:42:25,825: DEBUG - sept. 16 13:42:25 systemd[1]: Failed to start YunoHost Wifi Hotspot.'
2021-09-16 13:42:25,831: DEBUG - + ynh_print_log '[Error] sept. 16 13:42:24 systemd[1]: Starting YunoHost Wifi Hotspot...
2021-09-16 13:42:25,831: DEBUG - sept. 16 13:42:24 ynh-hotspot[8084]: Retrieving Yunohost settings... OK
2021-09-16 13:42:25,832: DEBUG - sept. 16 13:42:24 ynh-hotspot[8084]: [hotspot] Starting...
2021-09-16 13:42:25,832: DEBUG - sept. 16 13:42:25 ynh-hotspot[8084]: Traceback (most recent call last):
2021-09-16 13:42:25,832: DEBUG - sept. 16 13:42:25 ynh-hotspot[8084]:   File "<stdin>", line 1, in <module>
2021-09-16 13:42:25,832: DEBUG - sept. 16 13:42:25 ynh-hotspot[8084]: ImportError: No module named yaml
2021-09-16 13:42:25,832: DEBUG - sept. 16 13:42:25 ynh-hotspot[8084]: Set NAT
2021-09-16 13:42:25,833: DEBUG - sept. 16 13:42:25 ynh-hotspot[8084]: Set forwarding
2021-09-16 13:42:25,833: DEBUG - sept. 16 13:42:25 ynh-hotspot[8084]: Run hostapd
2021-09-16 13:42:25,833: DEBUG - sept. 16 13:42:25 ynh-hotspot[8084]: Job for hostapd.service failed because the control process exited with error code.
2021-09-16 13:42:25,833: DEBUG - sept. 16 13:42:25 ynh-hotspot[8084]: See "systemctl status hostapd.service" and "journalctl -xe" for details.
2021-09-16 13:42:25,833: DEBUG - sept. 16 13:42:25 systemd[1]: ynh-hotspot.service: Main process exited, code=exited, status=1/FAILURE
2021-09-16 13:42:25,834: DEBUG - sept. 16 13:42:25 systemd[1]: ynh-hotspot.service: Failed with result '\''exit-code'\''.
2021-09-16 13:42:25,834: DEBUG - sept. 16 13:42:25 systemd[1]: Failed to start YunoHost Wifi Hotspot.'
2021-09-16 13:42:25,834: DEBUG - + echo -e '[Error] sept. 16 13:42:24 systemd[1]: Starting YunoHost Wifi Hotspot...
2021-09-16 13:42:25,834: DEBUG - sept. 16 13:42:24 ynh-hotspot[8084]: Retrieving Yunohost settings... OK
2021-09-16 13:42:25,834: DEBUG - sept. 16 13:42:24 ynh-hotspot[8084]: [hotspot] Starting...
2021-09-16 13:42:25,835: DEBUG - sept. 16 13:42:25 ynh-hotspot[8084]: Traceback (most recent call last):
2021-09-16 13:42:25,835: DEBUG - sept. 16 13:42:25 ynh-hotspot[8084]:   File "<stdin>", line 1, in <module>
2021-09-16 13:42:25,835: DEBUG - sept. 16 13:42:25 ynh-hotspot[8084]: ImportError: No module named yaml
2021-09-16 13:42:25,835: DEBUG - sept. 16 13:42:25 ynh-hotspot[8084]: Set NAT
2021-09-16 13:42:25,835: DEBUG - sept. 16 13:42:25 ynh-hotspot[8084]: Set forwarding
2021-09-16 13:42:25,836: DEBUG - sept. 16 13:42:25 ynh-hotspot[8084]: Run hostapd
2021-09-16 13:42:25,836: DEBUG - sept. 16 13:42:25 ynh-hotspot[8084]: Job for hostapd.service failed because the control process exited with error code.
2021-09-16 13:42:25,836: DEBUG - sept. 16 13:42:25 ynh-hotspot[8084]: See "systemctl status hostapd.service" and "journalctl -xe" for details.
2021-09-16 13:42:25,836: DEBUG - sept. 16 13:42:25 systemd[1]: ynh-hotspot.service: Main process exited, code=exited, status=1/FAILURE
2021-09-16 13:42:25,836: DEBUG - sept. 16 13:42:25 systemd[1]: ynh-hotspot.service: Failed with result '\''exit-code'\''.
2021-09-16 13:42:25,836: DEBUG - sept. 16 13:42:25 systemd[1]: Failed to start YunoHost Wifi Hotspot.'
2021-09-16 13:42:25,837: DEBUG - + '[' -e systemd ']'
2021-09-16 13:42:25,837: DEBUG - + ynh_clean_check_starting
2021-09-16 13:42:25,837: DEBUG - + '[' -n '' ']'
2021-09-16 13:42:25,837: DEBUG - + '[' -n '' ']'
2021-09-16 13:42:25,837: DEBUG - + return 1
2021-09-16 13:42:25,837: WARNING - [Error] sept. 16 13:42:24 systemd[1]: Starting YunoHost Wifi Hotspot...
2021-09-16 13:42:25,838: WARNING - sept. 16 13:42:24 ynh-hotspot[8084]: Retrieving Yunohost settings... OK
2021-09-16 13:42:25,838: WARNING - sept. 16 13:42:24 ynh-hotspot[8084]: [hotspot] Starting...
2021-09-16 13:42:25,840: WARNING - sept. 16 13:42:25 ynh-hotspot[8084]: Traceback (most recent call last):
2021-09-16 13:42:25,840: WARNING - sept. 16 13:42:25 ynh-hotspot[8084]:   File "<stdin>", line 1, in <module>
2021-09-16 13:42:25,840: WARNING - sept. 16 13:42:25 ynh-hotspot[8084]: ImportError: No module named yaml
2021-09-16 13:42:25,841: WARNING - sept. 16 13:42:25 ynh-hotspot[8084]: Set NAT
2021-09-16 13:42:25,841: WARNING - sept. 16 13:42:25 ynh-hotspot[8084]: Set forwarding
2021-09-16 13:42:25,841: WARNING - sept. 16 13:42:25 ynh-hotspot[8084]: Run hostapd
2021-09-16 13:42:25,842: WARNING - sept. 16 13:42:25 ynh-hotspot[8084]: Job for hostapd.service failed because the control process exited with error code.
2021-09-16 13:42:25,842: WARNING - sept. 16 13:42:25 ynh-hotspot[8084]: See "systemctl status hostapd.service" and "journalctl -xe" for details.
2021-09-16 13:42:25,842: WARNING - sept. 16 13:42:25 systemd[1]: ynh-hotspot.service: Main process exited, code=exited, status=1/FAILURE
2021-09-16 13:42:25,843: WARNING - sept. 16 13:42:25 systemd[1]: ynh-hotspot.service: Failed with result 'exit-code'.
2021-09-16 13:42:25,843: WARNING - sept. 16 13:42:25 systemd[1]: Failed to start YunoHost Wifi Hotspot.
2021-09-16 13:42:25,843: DEBUG - + ynh_exit_properly
2021-09-16 13:42:25,844: DEBUG - + local exit_code=1
2021-09-16 13:42:25,844: DEBUG - + rm -rf /var/cache/yunohost/download/
2021-09-16 13:42:25,844: DEBUG - + '[' 1 -eq 0 ']'
2021-09-16 13:42:25,844: DEBUG - + trap '' EXIT
2021-09-16 13:42:25,844: DEBUG - + set +o errexit
2021-09-16 13:42:25,844: DEBUG - + set +o nounset
2021-09-16 13:42:25,845: DEBUG - + sleep 0.5
2021-09-16 13:42:26,334: DEBUG - + type -t ynh_clean_setup
2021-09-16 13:42:26,334: DEBUG - + ynh_clean_setup
2021-09-16 13:42:26,335: DEBUG - + ynh_clean_check_starting
2021-09-16 13:42:26,335: DEBUG - + '[' -n '' ']'
2021-09-16 13:42:26,335: DEBUG - + '[' -n '' ']'
2021-09-16 13:42:26,335: DEBUG - + exit 1
2021-09-16 13:42:27,338: ERROR - Impossible d’installer hotspot : Une erreur est survenue dans le script d’installation de l’application

**Comment by alexAubin** [comment]
Ah yes we probably still have some bits of python2 in there and  python-yaml (i.e. the python2 yaml lib) ain't installed in yunohost anymore ...

Can you try to `apt install python-yaml` and try again ?

**Comment by alexAubin** [comment]
(For folks interested, the relevant code is https://github.com/labriqueinternet/hotspot_ynh/blob/testing/conf/ynh-hotspot#L265-L266 )

**Comment by pascal-levasseur** [comment]
The python-yaml package was installed without problem.

But the Wifi Hotspot install failed again.

Log file link below
[Wifi_Hotspot_Log.txt](https://github.com/labriqueinternet/hotspot_ynh/files/7226281/Wifi_Hotspot_Log.txt)
in

**Comment by alexAubin** [comment]
Can you share the output of : `journalctl --no-hostname --no-pager -u hostapd -n 100`

**Comment by pascal-levasseur** [comment]
Since the tests will now take place on another yunohost instance for convinience,I am closing this issue and I reopen a new one
